/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import cadastro.CadUsuario;

import usuario.Autenticacao;
import cadastro.opCompra;
import cadastro.Estoque;
import cadastro.ProcessoVenda;
import cadastro.VerUsu;
import com.sun.jdi.connect.spi.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matheus_n_pereira
 */
public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
         setSize(854,480);
         setLocationRelativeTo(null);
        
    }
  
   


    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jComboBox1 = new javax.swing.JComboBox<>();
        desktop = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Compra = new javax.swing.JMenuItem();
        Venda = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        estoque = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktop.setForeground(new java.awt.Color(184, 176, 59));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/2 (1).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        desktop.add(jLabel2);
        jLabel2.setBounds(0, 0, 850, 470);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));

        jMenu1.setBackground(new java.awt.Color(0, 0, 0));
        jMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 2));
        jMenu1.setForeground(new java.awt.Color(184, 176, 59));
        jMenu1.setText("Cadastro");
        jMenu1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(184, 176, 59));
        jMenuItem1.setText("Cadastro funcionários");
        jMenuItem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 2));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItem2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(184, 176, 59));
        jMenuItem2.setText("Funcionários cadastrados");
        jMenuItem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 2));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 0, 0));
        jMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 2));
        jMenu2.setForeground(new java.awt.Color(184, 176, 59));
        jMenu2.setText("Compra e venda");
        jMenu2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        Compra.setBackground(new java.awt.Color(0, 0, 0));
        Compra.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Compra.setForeground(new java.awt.Color(184, 176, 59));
        Compra.setText("Compra de veiculos ");
        Compra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59)));
        Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompraActionPerformed(evt);
            }
        });
        jMenu2.add(Compra);

        Venda.setBackground(new java.awt.Color(0, 0, 0));
        Venda.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Venda.setForeground(new java.awt.Color(184, 176, 59));
        Venda.setText("Venda de veículos ");
        Venda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59)));
        Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendaActionPerformed(evt);
            }
        });
        jMenu2.add(Venda);

        jMenuBar1.add(jMenu2);

        jMenu5.setBackground(new java.awt.Color(0, 0, 0));
        jMenu5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 2));
        jMenu5.setForeground(new java.awt.Color(184, 176, 59));
        jMenu5.setText("Estoque");
        jMenu5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        estoque.setBackground(new java.awt.Color(0, 0, 0));
        estoque.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        estoque.setForeground(new java.awt.Color(184, 176, 59));
        estoque.setText("Estoque");
        estoque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 2));
        estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueActionPerformed(evt);
            }
        });
        jMenu5.add(estoque);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
     /*   CadUsuario cadusuario = new CadUsuario();
        cadusuario.setVisible(true);
        desktop.add(cadusuario);*/


    }//GEN-LAST:event_jMenu1ActionPerformed

    private void CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompraActionPerformed
        opCompra opcompra = new opCompra();
        opcompra.setVisible(true);
        desktop.add(opcompra);


    }//GEN-LAST:event_CompraActionPerformed

    private void VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendaActionPerformed

        ProcessoVenda Processovenda = new ProcessoVenda();
        Processovenda.setVisible(true);
        desktop.add(Processovenda);

    }//GEN-LAST:event_VendaActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        Estoque estoque = new Estoque();
        estoque.setVisible(true);
        desktop.add(estoque);

    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jLabel2.setVisible(false);
        CadUsuario cadusuario = new CadUsuario();
        cadusuario.setVisible(true);
        desktop.add(cadusuario);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueActionPerformed
Estoque estoque = new Estoque();
        estoque.setVisible(true);
        desktop.add(estoque);

    }//GEN-LAST:event_estoqueActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      VerUsu verusu = new VerUsu();
        verusu.setVisible(true);
        desktop.add(verusu);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Compra;
    private javax.swing.JMenuItem Venda;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem estoque;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
