/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cadastro;


import conecta.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import main.Principal;
import model.Compra;

/**
 *
 * @author pmath
 */
public class opCompra extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form opCompra
     */
    public opCompra() {
        initComponents();
          setSize(854,480);
        conexao = Conexao.conector();
    }
//metodo compra 

    private void compra() {
        String sql = "insert into carro (txtnomec,txtcpf,txtmarca,txtmodelo,txtanov,"
                + "txtdesc,txtplaca,txtmanuntencao,txtvalorc,txtdata) values(?,?,?,?,?,?,?,?,?,?)";

        Compra compra = new Compra();
        compra.settxtNomec(txtnomec.getText());
        compra.settxtCpf(txtcpf.getText());
        compra.settxtMarca(txtmarca.getText());
        compra.settxtModelo(txtmodelo.getText());
        compra.settxtAnov(txtanov.getText());
        compra.settxtDesc(txtdesc.getText());
        compra.settxtPlaca(txtplaca.getText());
        compra.settxtManuntencao(txtmanuntencao.getText());
        compra.settxtValorc(txtvalorc.getText());
        compra.settxtData(txtdata.getText());
        
        

        if(compra.gettxtNomec().equals(""))
            
        {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatorios ");
        }else{
            
        }
        
        
        try {
            pst = conexao.prepareStatement(sql);
           
            pst.setString(1, compra.gettxtNomec());
            pst.setString(2, compra.gettxtCpf());
            pst.setString(3, compra.gettxtMarca());
            pst.setString(4, compra.gettxtModelo());
            pst.setString(5, compra.gettxtAnov());
            pst.setString(6, compra.gettxtDesc());
            pst.setString(7, compra.gettxtPlaca());
            pst.setString(8, compra.gettxtManuntencao());
            pst.setString(9, compra.gettxtValorc());
            pst.setString(10, compra.gettxtData());
           
            
           

            if (txtanov.getText().isEmpty() || txtanov.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");
            } else {
                int adicionado = pst.executeUpdate();

                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Deseja confirmar a compra ? ");
                } else {
                    JOptionPane.showMessageDialog(null, "Ha um erro na inserção");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//Fim do método compra

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtanov = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtdesc = new javax.swing.JTextField();
        txtdata = new javax.swing.JTextField();
        txtnomec = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtcpf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtvalorc = new javax.swing.JTextField();
        txtmanuntencao = new javax.swing.JTextField();
        txtmanuntencao1 = new javax.swing.JTextField();
        txtplaca = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtid = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        txtplaca1 = new javax.swing.JTextField();

        jTextField5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);
        getContentPane().add(desktop);
        desktop.setBounds(0, 0, 0, 0);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(184, 176, 59));
        jLabel1.setText("Opção de compra");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(347, 12, 192, 32);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(184, 176, 59));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 60, 30, 24);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(184, 176, 59));
        jLabel3.setText("Digite nome do cliente");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(55, 126, 190, 24);

        txtanov.setBackground(new java.awt.Color(0, 0, 0));
        txtanov.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtanov.setForeground(new java.awt.Color(184, 176, 59));
        txtanov.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        txtanov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanovActionPerformed(evt);
            }
        });
        getContentPane().add(txtanov);
        txtanov.setBounds(350, 90, 180, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(184, 176, 59));
        jLabel4.setText("Digite CPF do cliente ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(55, 190, 174, 24);

        txtmodelo.setBackground(new java.awt.Color(0, 0, 0));
        txtmodelo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtmodelo.setForeground(new java.awt.Color(184, 176, 59));
        txtmodelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        getContentPane().add(txtmodelo);
        txtmodelo.setBounds(55, 345, 178, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(184, 176, 59));
        jLabel5.setText("Digite modelo do veículo ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(55, 315, 202, 24);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(184, 176, 59));
        jLabel6.setText("Digite o valor de compra");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(347, 315, 210, 24);

        txtmarca.setBackground(new java.awt.Color(0, 0, 0));
        txtmarca.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtmarca.setForeground(new java.awt.Color(184, 176, 59));
        txtmarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        txtmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmarcaActionPerformed(evt);
            }
        });
        getContentPane().add(txtmarca);
        txtmarca.setBounds(55, 281, 178, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(184, 176, 59));
        jLabel7.setText("Digite ano do veiculo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(347, 62, 280, 24);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(184, 176, 59));
        jLabel8.setText("Descrição do veículo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(347, 126, 280, 24);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(184, 176, 59));
        jLabel9.setText("Digite placa do veículo ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(347, 190, 187, 24);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(184, 176, 59));
        jLabel10.setText("Digite marca do veículo ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(55, 254, 210, 24);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(184, 176, 59));
        jLabel11.setText("Custo de manuntenção ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(347, 254, 200, 24);

        txtdesc.setBackground(new java.awt.Color(0, 0, 0));
        txtdesc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtdesc.setForeground(new java.awt.Color(184, 176, 59));
        txtdesc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        getContentPane().add(txtdesc);
        txtdesc.setBounds(347, 156, 178, 30);

        txtdata.setBackground(new java.awt.Color(0, 0, 0));
        txtdata.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtdata.setForeground(new java.awt.Color(184, 176, 59));
        txtdata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        getContentPane().add(txtdata);
        txtdata.setBounds(640, 90, 178, 30);

        txtnomec.setBackground(new java.awt.Color(0, 0, 0));
        txtnomec.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtnomec.setForeground(new java.awt.Color(184, 176, 59));
        txtnomec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        txtnomec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecActionPerformed(evt);
            }
        });
        getContentPane().add(txtnomec);
        txtnomec.setBounds(55, 156, 178, 30);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(184, 176, 59));
        jLabel13.setText("Digite a data da compra");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(639, 62, 200, 21);

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(184, 176, 59));
        jLabel14.setText("Para finalizar a compra ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(639, 126, 200, 21);

        txtcpf.setBackground(new java.awt.Color(0, 0, 0));
        txtcpf.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtcpf.setForeground(new java.awt.Color(184, 176, 59));
        txtcpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        txtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtcpf);
        txtcpf.setBounds(58, 220, 180, 30);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(184, 176, 59));
        jLabel12.setText("clique no botão confirmar ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(639, 156, 220, 21);

        txtvalorc.setBackground(new java.awt.Color(0, 0, 0));
        txtvalorc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtvalorc.setForeground(new java.awt.Color(184, 176, 59));
        txtvalorc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        getContentPane().add(txtvalorc);
        txtvalorc.setBounds(350, 350, 178, 30);

        txtmanuntencao.setBackground(new java.awt.Color(0, 0, 0));
        txtmanuntencao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtmanuntencao.setForeground(new java.awt.Color(184, 176, 59));
        txtmanuntencao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        getContentPane().add(txtmanuntencao);
        txtmanuntencao.setBounds(350, 280, 178, 30);

        txtmanuntencao1.setBackground(new java.awt.Color(0, 0, 0));
        txtmanuntencao1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtmanuntencao1.setForeground(new java.awt.Color(184, 176, 59));
        txtmanuntencao1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        getContentPane().add(txtmanuntencao1);
        txtmanuntencao1.setBounds(350, 280, 178, 30);

        txtplaca.setBackground(new java.awt.Color(0, 0, 0));
        txtplaca.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtplaca.setForeground(new java.awt.Color(184, 176, 59));
        txtplaca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        getContentPane().add(txtplaca);
        txtplaca.setBounds(347, 220, 178, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(184, 176, 59));
        jButton2.setText("CANCELAR");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(640, 260, 200, 46);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(184, 176, 59));
        jButton3.setText("CONFIRMAR");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(640, 200, 200, 46);

        txtid.setBackground(new java.awt.Color(0, 0, 0));
        txtid.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtid.setForeground(new java.awt.Color(184, 176, 59));
        txtid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid);
        txtid.setBounds(60, 90, 60, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/2 (1).jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 850, 450);

        txtplaca1.setBackground(new java.awt.Color(0, 0, 0));
        txtplaca1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtplaca1.setForeground(new java.awt.Color(184, 176, 59));
        txtplaca1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        getContentPane().add(txtplaca1);
        txtplaca1.setBounds(347, 220, 178, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
      compra();  
      jButton3.setVisible(false);
      Principal principal = new Principal();
principal.setVisible(true);
        desktop.add(principal);
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtanovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanovActionPerformed

    private void txtmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmarcaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jButton2.setVisible(false);
       Principal principal = new Principal();
principal.setVisible(true);
        desktop.add(principal);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtnomecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecActionPerformed

    private void txtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtanov;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtdata;
    private javax.swing.JTextField txtdesc;
    private javax.swing.JPasswordField txtid;
    private javax.swing.JTextField txtmanuntencao;
    private javax.swing.JTextField txtmanuntencao1;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtnomec;
    private javax.swing.JTextField txtplaca;
    private javax.swing.JTextField txtplaca1;
    private javax.swing.JTextField txtvalorc;
    // End of variables declaration//GEN-END:variables
}
