/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cadastro;
import conecta.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import cadastro.opCompra;
import java.awt.HeadlessException;
import java.sql.SQLException;
import main.Principal;
import model.Venda;
/**
 *
 * @author pmath
 */
public class opVenda extends javax.swing.JInternalFrame {

    
    
    
   Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    /**
     * Creates new form opVenda
     */
    public opVenda() {
        initComponents();
         setSize(854,480);
        conexao = Conexao.conector();
    }
    
     private void venda() {
        String sql = "delete from carro where id_user = ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtid.getText());

            int excluir = JOptionPane.showConfirmDialog(null, "Confirma a venda ?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (excluir == JOptionPane.YES_OPTION) {
                int excluido = pst.executeUpdate();
                if (excluido > 0) {
                    JOptionPane.showMessageDialog(null, "Venda realizado com sucesso");
                    anov.setText(null);
                    
                    txtid.setText(null);
                    txtmarca.setText(null);
                    txtmodelo.setText(null);
                    
                    txtdesc.setText(null);
                    txtplaca.setText(null);
                    txtprecov.setText(null);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }
    
      //metodo consultar 
    private void pesquisar() {
     String sql = "Select * from carro where txtid = ?";

        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtid.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtmarca.setText(rs.getString(2));
                txtmodelo.setText(rs.getString(3));
                txtdesc.setText(rs.getString(4));
                txtplaca.setText(rs.getString(5));
                txtprecov.setText(rs.getString(6));
                
            } else {
                txtmarca.setText(null);
                txtmodelo.setText(null);
                txtdesc.setText(null);
                txtplaca.setText(null);
                txtprecov.setText(null);

                JOptionPane.showMessageDialog(null, "Usuário não encontrado");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtplaca = new javax.swing.JTextField();
        anov = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtmodelo = new javax.swing.JTextField();
        desktop = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtprecov = new javax.swing.JTextField();
        txtdesc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(184, 176, 59));
        jLabel2.setText("Digite o código de compra do veículo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 60, 380, 24);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(184, 176, 59));
        jLabel3.setText("Ano");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(46, 138, 100, 24);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(184, 176, 59));
        jLabel4.setText("Modelo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(46, 286, 59, 24);

        txtmarca.setBackground(new java.awt.Color(0, 0, 0));
        txtmarca.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtmarca.setForeground(new java.awt.Color(184, 176, 59));
        txtmarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        getContentPane().add(txtmarca);
        txtmarca.setBounds(46, 240, 185, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(184, 176, 59));
        jLabel5.setText("Descrição do veículo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(302, 138, 230, 24);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(184, 176, 59));
        jLabel6.setText("Marca");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(46, 210, 140, 24);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(184, 176, 59));
        jLabel7.setText("Placa");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(302, 210, 150, 24);

        txtplaca.setBackground(new java.awt.Color(0, 0, 0));
        txtplaca.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtplaca.setForeground(new java.awt.Color(184, 176, 59));
        txtplaca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        getContentPane().add(txtplaca);
        txtplaca.setBounds(302, 240, 212, 30);

        anov.setBackground(new java.awt.Color(0, 0, 0));
        anov.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        anov.setForeground(new java.awt.Color(184, 176, 59));
        anov.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        getContentPane().add(anov);
        anov.setBounds(46, 170, 79, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(184, 176, 59));
        jButton2.setText("Cancelar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 260, 180, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(184, 176, 59));
        jButton3.setText("Confirmar");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(620, 210, 180, 30);

        txtmodelo.setBackground(new java.awt.Color(0, 0, 0));
        txtmodelo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtmodelo.setForeground(new java.awt.Color(184, 176, 59));
        txtmodelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        txtmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmodeloActionPerformed(evt);
            }
        });
        getContentPane().add(txtmodelo);
        txtmodelo.setBounds(46, 316, 185, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(184, 176, 59));
        jButton1.setText("Pesquisar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        desktop.add(jButton1);
        jButton1.setBounds(410, 90, 100, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(184, 176, 59));
        jLabel8.setText("Valor de venda");
        desktop.add(jLabel8);
        jLabel8.setBounds(300, 290, 207, 24);

        txtprecov.setBackground(new java.awt.Color(0, 0, 0));
        txtprecov.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtprecov.setForeground(new java.awt.Color(184, 176, 59));
        txtprecov.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        desktop.add(txtprecov);
        txtprecov.setBounds(300, 320, 220, 30);

        txtdesc.setBackground(new java.awt.Color(0, 0, 0));
        txtdesc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtdesc.setForeground(new java.awt.Color(184, 176, 59));
        txtdesc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        desktop.add(txtdesc);
        txtdesc.setBounds(302, 170, 212, 30);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(184, 176, 59));
        jLabel11.setText("Deseja confirmar a venda");
        desktop.add(jLabel11);
        jLabel11.setBounds(620, 170, 210, 24);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(184, 176, 59));
        jLabel1.setText("Opção de venda");
        desktop.add(jLabel1);
        jLabel1.setBounds(347, 12, 177, 32);

        txtid.setBackground(new java.awt.Color(0, 0, 0));
        txtid.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtid.setForeground(new java.awt.Color(184, 176, 59));
        txtid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        desktop.add(txtid);
        txtid.setBounds(300, 90, 86, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/2 (1).jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        desktop.add(jLabel9);
        jLabel9.setBounds(0, 0, 850, 450);

        getContentPane().add(desktop);
        desktop.setBounds(0, 0, 850, 450);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(184, 176, 59));
        jLabel10.setText("Digite o código de compra do veículo");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(260, 60, 380, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jButton3.setVisible(false);
    venda();  

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmodeloActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     Principal principal = new Principal();
     principal.setVisible(true);
      desktop.add(principal);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        pesquisar();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField anov;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtdesc;
    private javax.swing.JPasswordField txtid;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtplaca;
    private javax.swing.JTextField txtprecov;
    // End of variables declaration//GEN-END:variables
}
