/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastro;

import javax.swing.JOptionPane;
import conecta.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import cadastro.opCompra;
import main.Principal;
import main.Vendaop;
import model.Venda;
/**
 *
 * @author matheus_n_pereira
 */
public class ProcessoVenda extends javax.swing.JInternalFrame {
    
     Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    

    /**
     * Creates new form ProcessoVenda
     */
    public ProcessoVenda() {
        initComponents();
         setSize(854,480);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdatavenda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcpfcomp1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sim = new javax.swing.JButton();
        nao = new javax.swing.JButton();
        txtnomec = new javax.swing.JTextField();
        desktop = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(184, 176, 59));
        jLabel1.setText("Processo de venda");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(320, 10, 205, 32);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(184, 176, 59));
        jLabel2.setText("Digite CPF do comprador ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(62, 134, 215, 24);

        txtdatavenda.setBackground(new java.awt.Color(0, 0, 0));
        txtdatavenda.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtdatavenda.setForeground(new java.awt.Color(184, 176, 59));
        txtdatavenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        txtdatavenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatavendaActionPerformed(evt);
            }
        });
        getContentPane().add(txtdatavenda);
        txtdatavenda.setBounds(60, 240, 220, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(184, 176, 59));
        jLabel3.setText("Digite nome do comprador ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(62, 70, 220, 24);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(184, 176, 59));
        jLabel5.setText("Data venda");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 210, 207, 24);

        txtcpfcomp1.setBackground(new java.awt.Color(0, 0, 0));
        txtcpfcomp1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtcpfcomp1.setForeground(new java.awt.Color(184, 176, 59));
        txtcpfcomp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        getContentPane().add(txtcpfcomp1);
        txtcpfcomp1.setBounds(60, 170, 220, 30);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(184, 176, 59));
        jLabel6.setText("Deseja continuar a venda ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(500, 90, 220, 24);

        sim.setBackground(new java.awt.Color(0, 0, 0));
        sim.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sim.setForeground(new java.awt.Color(184, 176, 59));
        sim.setText("SIM");
        sim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simActionPerformed(evt);
            }
        });
        getContentPane().add(sim);
        sim.setBounds(500, 140, 210, 30);

        nao.setBackground(new java.awt.Color(0, 0, 0));
        nao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nao.setForeground(new java.awt.Color(184, 176, 59));
        nao.setText("NÃO");
        nao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoActionPerformed(evt);
            }
        });
        getContentPane().add(nao);
        nao.setBounds(500, 180, 210, 30);

        txtnomec.setBackground(new java.awt.Color(0, 0, 0));
        txtnomec.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtnomec.setForeground(new java.awt.Color(184, 176, 59));
        txtnomec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 3));
        txtnomec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomecActionPerformed(evt);
            }
        });
        getContentPane().add(txtnomec);
        txtnomec.setBounds(62, 100, 215, 30);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(desktop);
        desktop.setBounds(0, 0, 1718, 0);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/2 (1).jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 850, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoActionPerformed
 Principal principal = new Principal();
principal.setVisible(true);
        desktop.add(principal);
    }//GEN-LAST:event_naoActionPerformed

    private void simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simActionPerformed

Vendaop teste = new Vendaop();
teste.setVisible(true);
        teste.add(teste);
    }//GEN-LAST:event_simActionPerformed

    private void txtnomecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomecActionPerformed

    private void txtdatavendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatavendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatavendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton nao;
    private javax.swing.JButton sim;
    private javax.swing.JTextField txtcpfcomp1;
    private javax.swing.JTextField txtdatavenda;
    private javax.swing.JTextField txtnomec;
    // End of variables declaration//GEN-END:variables

    
    }

    
    

    
    

