/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastro;

import conecta.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.Principal;



/**
 *
 * @author matheus_n_pereira
 */
public class VerUsu extends javax.swing.JInternalFrame {
    
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    

    /**
     * Creates new form VerUsu
     */
    public VerUsu() {
        initComponents();
         setSize(854,480);
      conexao = Conexao.conector();
    PreparedStatement pst = null;
    ResultSet rs = null;
    consultar();
     
    }

    private void consultar() {
        String sql = "Select * from funcionario";
        try {
            pst = conexao.prepareStatement(sql);
         
            rs = pst.executeQuery();
            DefaultTableModel model =(DefaultTableModel) tbusu.getModel();
   model.setNumRows(0);
 
   while(rs.next())
   {
       model.addRow(new Object[]
       {
          //retorna os dados da tabela do BD, cada campo e um coluna.
          rs.getString("id_user"),
          rs.getString("nm_user"),
          rs.getString("ds_login")
       });
  }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbusu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        tbusu.setBackground(new java.awt.Color(0, 0, 0));
        tbusu.setForeground(new java.awt.Color(184, 176, 59));
        tbusu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Login"
            }
        ));
        tbusu.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tbusu.setSelectionForeground(new java.awt.Color(184, 176, 59));
        jScrollPane1.setViewportView(tbusu);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 50, 460, 270);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(184, 176, 59));
        jLabel2.setText("Funcionários");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 10, 160, 32);

        voltar.setBackground(new java.awt.Color(0, 0, 0));
        voltar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        voltar.setForeground(new java.awt.Color(184, 176, 59));
        voltar.setText("Voltar");
        voltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(184, 176, 59), 2));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(360, 340, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/2 (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 450);
        getContentPane().add(desktop);
        desktop.setBounds(0, 0, 850, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        Principal principal = new Principal();
        principal.setVisible(true);
        desktop.add(principal);

    }//GEN-LAST:event_voltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbusu;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
